// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUzKrybJfIZWAiq2xksB57qoUNCcy7GpY',
    appId: '1:816421572269:web:e835b83c8e0e58115d4024',
    messagingSenderId: '816421572269',
    projectId: 'mynotes-flutter-project-415fb',
    authDomain: 'mynotes-flutter-project-415fb.firebaseapp.com',
    storageBucket: 'mynotes-flutter-project-415fb.appspot.com',
    measurementId: 'G-VG1ZHXW6ZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWDUCo31-AplcooUBgOP_D2VLtst4wt8Y',
    appId: '1:816421572269:android:91f53e162c8fa1445d4024',
    messagingSenderId: '816421572269',
    projectId: 'mynotes-flutter-project-415fb',
    storageBucket: 'mynotes-flutter-project-415fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8XRmGu692NODabfZZUEu9B7XwvcOOBwo',
    appId: '1:816421572269:ios:ac77303d046b595b5d4024',
    messagingSenderId: '816421572269',
    projectId: 'mynotes-flutter-project-415fb',
    storageBucket: 'mynotes-flutter-project-415fb.appspot.com',
    iosClientId: '816421572269-o5rd4unapfu3c3q3sim30igganalakms.apps.googleusercontent.com',
    iosBundleId: 'se.pixolity.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8XRmGu692NODabfZZUEu9B7XwvcOOBwo',
    appId: '1:816421572269:ios:ac77303d046b595b5d4024',
    messagingSenderId: '816421572269',
    projectId: 'mynotes-flutter-project-415fb',
    storageBucket: 'mynotes-flutter-project-415fb.appspot.com',
    iosClientId: '816421572269-o5rd4unapfu3c3q3sim30igganalakms.apps.googleusercontent.com',
    iosBundleId: 'se.pixolity.mynotes',
  );
}
